### ISSUE TITLE
Application screenshots in Readme

### ISSUE THREAD

**Issue by codingjeremy** [android/animation#16]
<a href="https://github.com/metc"><img src="https://avatars1.githubusercontent.com/u/229670?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [metc](https://github.com/metc)**
_Tuesday Jan 26, 2016 at 20:23 GMT_
_Originally opened as https://github.com/googlesamples/android-Interpolator/issues/4_

----

Hi,

Since commit a001031c33499dcd1e883560a25b99c881442fa8, the two application screenshots are not displayed correctly in the [README](https://github.com/googlesamples/android-Interpolator/blob/master/README.md) file.

**Comment by codingjeremy** [comment]
<a href="https://github.com/keyboardsurfer"><img src="https://avatars2.githubusercontent.com/u/336005?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [keyboardsurfer](https://github.com/keyboardsurfer)**
_Wednesday Jan 27, 2016 at 11:10 GMT_

----

Internal: 26808632

**Comment by codingjeremy** [comment]
<a href="https://github.com/metc"><img src="https://avatars1.githubusercontent.com/u/229670?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [metc](https://github.com/metc)**
_Sunday Apr 03, 2016 at 14:52 GMT_

----

Ping @keyboardsurfer

**Comment by keyboardsurfer** [comment]
Resolved in https://github.com/android/animation/tree/master/Interpolator
